ALTER TABLE `sa45grp13ca`.`productdata` 
CHANGE COLUMN `description` `description` VARCHAR(255) NULL DEFAULT NULL ;

INSERT INTO `sa45grp13ca`.`productdata` (`partname`, `unitprice`, `description`, `color`, `dimension`, `supplierid`, `reorderpoint`, `minorder`, `shelflocation`, `category`) VALUES ('ToyotaChassis', '4000', 'CarChasis', 'black', '4000', '101', '10', '5', '4', 'Part Replacement');
INSERT INTO `sa45grp13ca`.`productdata` (`partname`, `unitprice`, `description`, `color`, `dimension`, `supplierid`, `reorderpoint`, `minorder`, `shelflocation`, `category`) VALUES ('MichilinCarTyre', '150', 'tyre', 'black', '600', '103', '200', '150', '7', 'Tyres');
INSERT INTO `sa45grp13ca`.`productdata` (`partname`, `unitprice`, `description`, `color`, `dimension`, `supplierid`, `reorderpoint`, `minorder`, `shelflocation`, `category`) VALUES ('TransmissionShaft', '600', 'TransmissionShaft', 'black', '2000', '103', '20', '10', '7', 'Part Replacement');
INSERT INTO `sa45grp13ca`.`productdata` (`partname`, `unitprice`, `description`, `color`, `dimension`, `supplierid`, `reorderpoint`, `minorder`, `shelflocation`, `category`) VALUES ('TyreRim', '300', 'TyreRim', 'silver', '500', '120', '40', '20', '5', 'Tyres');
INSERT INTO `sa45grp13ca`.`productdata` (`partname`, `unitprice`, `description`, `color`, `dimension`, `supplierid`, `reorderpoint`, `minorder`, `shelflocation`, `category`) VALUES ('RadiatorFluid', '80', 'RadiatorFluid', 'orange', '100', '121', '100', '40', '8', 'Car Engine');
INSERT INTO `sa45grp13ca`.`productdata` (`partname`, `unitprice`, `description`, `color`, `dimension`, `supplierid`, `reorderpoint`, `minorder`, `shelflocation`, `category`) VALUES ('MotorFluid', '80', 'MotorFluid', 'yellow', '100', '130', '100', '40', '8', 'Car Engine');
INSERT INTO `sa45grp13ca`.`productdata` (`partname`, `unitprice`, `description`, `color`, `dimension`, `supplierid`, `reorderpoint`, `minorder`, `shelflocation`, `category`) VALUES ('CarSeat', '100', 'seat', 'grey', '1200', '135', '200', '50', '9', 'Part Replacement');
INSERT INTO `sa45grp13ca`.`productdata` (`partname`, `unitprice`, `description`, `color`, `dimension`, `supplierid`, `reorderpoint`, `minorder`, `shelflocation`, `category`) VALUES ('WindScreen', '900', 'windscreen', 'transparent', '1800', '138', '100', '50', '6', 'Part Replacement');
INSERT INTO `sa45grp13ca`.`productdata` (`partname`, `unitprice`, `description`, `color`, `dimension`, `supplierid`, `reorderpoint`, `minorder`, `shelflocation`, `category`) VALUES ('RearViewMirror', '150', 'RearViewMirror', 'green', '300', '134', '20', '10', '5', 'Accessories');
INSERT INTO `sa45grp13ca`.`productdata` (`partname`, `unitprice`, `description`, `color`, `dimension`, `supplierid`, `reorderpoint`, `minorder`, `shelflocation`, `category`) VALUES ('sideMirror', '150', 'sideMirror', 'green', '300', '128', '20', '10', '5', 'Accessories');
INSERT INTO `sa45grp13ca`.`productdata` (`partname`, `unitprice`, `description`, `color`, `dimension`, `supplierid`, `reorderpoint`, `minorder`, `shelflocation`, `category`) VALUES ('WindScreenWiper', '20', 'wiper', 'black', '1200', '122', '100', '20', '6', 'Part Replacement');
INSERT INTO `sa45grp13ca`.`productdata` (`partname`, `unitprice`, `description`, `color`, `dimension`, `supplierid`, `reorderpoint`, `minorder`, `shelflocation`, `category`) VALUES ('ToyotaEngine', '10000', 'engine', 'silver', '700', '132', '10', '1', '5', 'Car Engine');
INSERT INTO `sa45grp13ca`.`productdata` (`partname`, `unitprice`, `description`, `color`, `dimension`, `supplierid`, `reorderpoint`, `minorder`, `shelflocation`, `category`) VALUES ('Seatbelt', '50', 'seatbelt', 'grey ', '1000', '139', '110', '50', '5', 'Accessories');


INSERT INTO `sa45grp13ca`.`productdata` (`partname`, `unitprice`, `description`, `color`, `dimension`, `supplierid`, `reorderpoint`, `minorder`, `shelflocation`, `category`) VALUES ('Legs', '500.00', 'Rubber-coated ', 'Beige', '50', '106', '10', '5', '3', 'Tyres');
INSERT INTO `sa45grp13ca`.`productdata` (`partname`, `unitprice`, `description`, `color`, `dimension`, `supplierid`, `reorderpoint`, `minorder`, `shelflocation`, `category`) VALUES ('Sound System - 1500', '1650.50', 'Sound System', 'Black', '30', '119', '5', '10', '1', 'Audio');
INSERT INTO `sa45grp13ca`.`productdata` (`partname`, `unitprice`, `description`, `color`, `dimension`, `supplierid`, `reorderpoint`, `minorder`, `shelflocation`, `category`) VALUES ('Mighty Glue', '50.00', 'For repairing tyres', 'Bluish White', '10', '125', '40', '50', '1', 'Tyre Maintenance');
INSERT INTO `sa45grp13ca`.`productdata` (`partname`, `unitprice`, `description`, `color`, `dimension`, `supplierid`, `reorderpoint`, `minorder`, `shelflocation`, `category`) VALUES ('CloudMove', '650', 'light wheels', 'Grey', '100', '110', '12', '12', '4', 'Tyres');
INSERT INTO `sa45grp13ca`.`productdata` (`partname`, `unitprice`, `description`, `color`, `dimension`, `supplierid`, `reorderpoint`, `minorder`, `shelflocation`, `category`) VALUES ('DinoGuard', '130', 'sprayon protection', 'Red', '13.5', '129', '50', '100', '2', 'Car Care');
INSERT INTO `sa45grp13ca`.`productdata` (`partname`, `unitprice`, `description`, `color`, `dimension`, `supplierid`, `reorderpoint`, `minorder`, `shelflocation`, `category`) VALUES ('Windscreen CX130', '300', 'for Honda Vezel(3rd Party)', 'Transparent', '130', '111', '2', '1', '5', 'Part Replacement');
INSERT INTO `sa45grp13ca`.`productdata` (`partname`, `unitprice`, `description`, `color`, `dimension`, `supplierid`, `reorderpoint`, `minorder`, `shelflocation`, `category`) VALUES ('Bag Organizer', '26', 'for side of driver seat', 'Brown', '35', '102', '10', '5', '2', 'Accessories');
INSERT INTO `sa45grp13ca`.`productdata` (`partname`, `unitprice`, `description`, `color`, `dimension`, `supplierid`, `reorderpoint`, `minorder`, `shelflocation`, `category`) VALUES ('PaperThin Glue', '10.35', 'for sideview mirrors', 'White', '5', '128', '10', '30', '1', 'Car Repairs');
INSERT INTO `sa45grp13ca`.`productdata` (`partname`, `unitprice`, `description`, `color`, `dimension`, `supplierid`, `reorderpoint`, `minorder`, `shelflocation`, `category`) VALUES ('WideView Mirror', '30', 'backview mirror', 'Black', '25', '119', '5', '2', '2', 'Accessories');
INSERT INTO `sa45grp13ca`.`productdata` (`partname`, `unitprice`, `description`, `color`, `dimension`, `supplierid`, `reorderpoint`, `minorder`, `shelflocation`, `category`) VALUES ('SpeedZeng', '400', 'engine oil', 'white', '30', '119', '3', '1', '2', 'Car Engine');

INSERT INTO `sa45grp13ca`.`productdata` (`partname`, `unitprice`, `description`, `color`, `dimension`, `supplierid`, `reorderpoint`, `minorder`, `shelflocation`, `category`) VALUES ('BANO', '25', 'lubricants', 'yellow', '8', '106', '25', '3', '2', 'Car Engine');
INSERT INTO `sa45grp13ca`.`productdata` (`partname`, `unitprice`, `description`, `color`, `dimension`, `supplierid`, `reorderpoint`, `minorder`, `shelflocation`, `category`) VALUES ('M4', '15', 'light bulb', 'tea', '2', '105', '10', '5', '4', 'Car Repairs');
INSERT INTO `sa45grp13ca`.`productdata` (`partname`, `unitprice`, `description`, `color`, `dimension`, `supplierid`, `reorderpoint`, `minorder`, `shelflocation`, `category`) VALUES ('BADYEAR', '130', 'tyre for Lamborghini', 'black', '30', '127', '8', '2', '5', 'Tyres');
INSERT INTO `sa45grp13ca`.`productdata` (`partname`, `unitprice`, `description`, `color`, `dimension`, `supplierid`, `reorderpoint`, `minorder`, `shelflocation`, `category`) VALUES ('BRIDGE', '180', 'tyre', 'black', '30', '107', '20', '4', '3', 'Tyres');
INSERT INTO `sa45grp13ca`.`productdata` (`partname`, `unitprice`, `description`, `color`, `dimension`, `supplierid`, `reorderpoint`, `minorder`, `shelflocation`, `category`) VALUES ('SPARK', '105', 'spark plug', 'silver', '6', '116', '20', '1', '2', 'Car Repairs');
INSERT INTO `sa45grp13ca`.`productdata` (`partname`, `unitprice`, `description`, `color`, `dimension`, `supplierid`, `reorderpoint`, `minorder`, `shelflocation`, `category`) VALUES ('STONE', '95', 'battery', 'grey', '25', '129', '6', '1', '1', 'Car Repairs');
INSERT INTO `sa45grp13ca`.`productdata` (`partname`, `unitprice`, `description`, `color`, `dimension`, `supplierid`, `reorderpoint`, `minorder`, `shelflocation`, `category`) VALUES ('WOODEN', '6', 'seat accessories', 'blue', '5', '103', '18', '4', '4', 'Accessories');
INSERT INTO `sa45grp13ca`.`productdata` (`partname`, `unitprice`, `description`, `color`, `dimension`, `supplierid`, `reorderpoint`, `minorder`, `shelflocation`, `category`) VALUES ('TTS', '12', 'Shampoo', 'pink', '3', '120', '30', '2', '2', 'Accessories');
INSERT INTO `sa45grp13ca`.`productdata` (`partname`, `unitprice`, `description`, `color`, `dimension`, `supplierid`, `reorderpoint`, `minorder`, `shelflocation`, `category`) VALUES ('SPEED', '110', 'spark pads', 'red', '12', '114', '12', '2', '3', 'Part Replacement');
INSERT INTO `sa45grp13ca`.`productdata` (`partname`, `unitprice`, `description`, `color`, `dimension`, `supplierid`, `reorderpoint`, `minorder`, `shelflocation`, `category`) VALUES ('RAZERR', '800', 'horns for luxury car', 'gold', '8', '108', '18', '4', '2', 'Accessories');
