ALTER TABLE `sa45grp13ca`.`productdata` 
CHANGE COLUMN `description` `description` VARCHAR(255) NULL DEFAULT NULL ;

INSERT INTO `sa45grp13ca`.`productdata` (`partname`, `unitprice`, `description`, `color`, `dimension`, `supplierid`, `reorderpoint`, `minorder`, `shelflocation`, `category`) VALUES ('ToyotaChassis', '4000', 'CarChasis', 'black', '4000', '101', '10', '5', '4', 'Part Replacement');
INSERT INTO `sa45grp13ca`.`productdata` (`partname`, `unitprice`, `description`, `color`, `dimension`, `supplierid`, `reorderpoint`, `minorder`, `shelflocation`, `category`) VALUES ('MichilinCarTyre', '150', 'tyre', 'black', '600', '103', '200', '150', '7', 'Tyres');
INSERT INTO `sa45grp13ca`.`productdata` (`partname`, `unitprice`, `description`, `color`, `dimension`, `supplierid`, `reorderpoint`, `minorder`, `shelflocation`, `category`) VALUES ('TransmissionShaft', '600', 'TransmissionShaft', 'black', '2000', '103', '20', '10', '7', 'Part Replacement');
INSERT INTO `sa45grp13ca`.`productdata` (`partname`, `unitprice`, `description`, `color`, `dimension`, `supplierid`, `reorderpoint`, `minorder`, `shelflocation`, `category`) VALUES ('TyreRim', '300', 'TyreRim', 'silver', '500', '120', '40', '20', '5', 'Tyres');
INSERT INTO `sa45grp13ca`.`productdata` (`partname`, `unitprice`, `description`, `color`, `dimension`, `supplierid`, `reorderpoint`, `minorder`, `shelflocation`, `category`) VALUES ('RadiatorFluid', '80', 'RadiatorFluid', 'orange', '100', '121', '100', '40', '8', 'Car Engine');
INSERT INTO `sa45grp13ca`.`productdata` (`partname`, `unitprice`, `description`, `color`, `dimension`, `supplierid`, `reorderpoint`, `minorder`, `shelflocation`, `category`) VALUES ('MotorFluid', '80', 'MotorFluid', 'yellow', '100', '132', '100', '40', '8', 'Car Engine');
INSERT INTO `sa45grp13ca`.`productdata` (`partname`, `unitprice`, `description`, `color`, `dimension`, `supplierid`, `reorderpoint`, `minorder`, `shelflocation`, `category`) VALUES ('CarSeat', '100', 'seat', 'grey', '1200', '140', '200', '50', '9', 'Part Replacement');
INSERT INTO `sa45grp13ca`.`productdata` (`partname`, `unitprice`, `description`, `color`, `dimension`, `supplierid`, `reorderpoint`, `minorder`, `shelflocation`, `category`) VALUES ('WindScreen', '900', 'windscreen', 'transparent', '1800', '140', '100', '50', '6', 'Part Replacement');
INSERT INTO `sa45grp13ca`.`productdata` (`partname`, `unitprice`, `description`, `color`, `dimension`, `supplierid`, `reorderpoint`, `minorder`, `shelflocation`, `category`) VALUES ('RearViewMirror', '150', 'RearViewMirror', 'green', '300', '151', '20', '10', '5', 'Accessories');
INSERT INTO `sa45grp13ca`.`productdata` (`partname`, `unitprice`, `description`, `color`, `dimension`, `supplierid`, `reorderpoint`, `minorder`, `shelflocation`, `category`) VALUES ('sideMirror', '150', 'sideMirror', 'green', '300', '151', '20', '10', '5', 'Accessories');
INSERT INTO `sa45grp13ca`.`productdata` (`partname`, `unitprice`, `description`, `color`, `dimension`, `supplierid`, `reorderpoint`, `minorder`, `shelflocation`, `category`) VALUES ('WindScreenWiper', '20', 'wiper', 'black', '1200', '122', '100', '20', '6', 'Part Replacement');
INSERT INTO `sa45grp13ca`.`productdata` (`partname`, `unitprice`, `description`, `color`, `dimension`, `supplierid`, `reorderpoint`, `minorder`, `shelflocation`, `category`) VALUES ('ToyotaEngine', '10000', 'engine', 'silver', '700', '136', '10', '1', '5', 'Car Engine');
INSERT INTO `sa45grp13ca`.`productdata` (`partname`, `unitprice`, `description`, `color`, `dimension`, `supplierid`, `reorderpoint`, `minorder`, `shelflocation`, `category`) VALUES ('Seatbelt', '50', 'seatbelt', 'gey ', '1000', '140', '200', '50', '5', 'Accessories');


INSERT INTO `sa45grp13ca`.`productdata` (`partname`, `unitprice`, `description`, `color`, `dimension`, `supplierid`, `reorderpoint`, `minorder`, `shelflocation`, `category`) VALUES ('Legs', '500.00', 'Rubber-coated ', 'Beige', '50', '106', '10', '5', '3', 'Tyres');
INSERT INTO `sa45grp13ca`.`productdata` (`partname`, `unitprice`, `description`, `color`, `dimension`, `supplierid`, `reorderpoint`, `minorder`, `shelflocation`, `category`) VALUES ('Sound System - 1500', '1650.50', 'Sound System', 'Black', '30', '119', '5', '10', '1', 'Audio');
INSERT INTO `sa45grp13ca`.`productdata` (`partname`, `unitprice`, `description`, `color`, `dimension`, `supplierid`, `reorderpoint`, `minorder`, `shelflocation`, `category`) VALUES ('Mighty Glue', '50.00', 'For repairing tyres', 'Bluish White', '10', '125', '40', '50', '1', 'Tyre Maintenance');
INSERT INTO `sa45grp13ca`.`productdata` (`partname`, `unitprice`, `description`, `color`, `dimension`, `supplierid`, `reorderpoint`, `minorder`, `shelflocation`, `category`) VALUES ('CloudMove', '650', 'light wheels', 'Grey', '100', '110', '12', '12', '4', 'Tyres');
INSERT INTO `sa45grp13ca`.`productdata` (`partname`, `unitprice`, `description`, `color`, `dimension`, `supplierid`, `reorderpoint`, `minorder`, `shelflocation`, `category`) VALUES ('DinoGuard', '130', 'sprayon protection', 'Red', '13.5', '129', '50', '100', '2', 'Car Care');
INSERT INTO `sa45grp13ca`.`productdata` (`partname`, `unitprice`, `description`, `color`, `dimension`, `supplierid`, `reorderpoint`, `minorder`, `shelflocation`, `category`) VALUES ('Windscreen CX130', '300', 'for Honda Vezel(3rd Party)', 'Transparent', '130', '111', '2', '1', '5', 'Part Replacement');
INSERT INTO `sa45grp13ca`.`productdata` (`partname`, `unitprice`, `description`, `color`, `dimension`, `supplierid`, `reorderpoint`, `minorder`, `shelflocation`, `category`) VALUES ('Bag Organizer', '26', 'for side of driver seat', 'Brown', '35', '102', '10', '5', '2', 'Accessories');
INSERT INTO `sa45grp13ca`.`productdata` (`partname`, `unitprice`, `description`, `color`, `dimension`, `supplierid`, `reorderpoint`, `minorder`, `shelflocation`, `category`) VALUES ('PaperThin Glue', '10.35', 'for sideview mirrors', 'White', '5', '128', '10', '30', '1', 'Car Repairs');
INSERT INTO `sa45grp13ca`.`productdata` (`partname`, `unitprice`, `description`, `color`, `dimension`, `supplierid`, `reorderpoint`, `minorder`, `shelflocation`, `category`) VALUES ('WideView Mirror', '30', 'backview mirror', 'Black', '25', '119', '5', '2', '2', 'Accessories');
INSERT INTO `sa45grp13ca`.`productdata` (`partname`, `unitprice`, `description`, `color`, `dimension`, `supplierid`, `reorderpoint`, `minorder`, `shelflocation`, `category`) VALUES ('SpeedZeng', '400', 'engine oil', 'white', '30', '119', '3', '1', '2', 'Car Engine');
